
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import os


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def print_try(val):
    print(f"button {val}")

def open_win_rec():
    os.system("record.py")


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_1
)

canvas.create_text(
    178.0,
    68.0,
    anchor="nw",
    text="楽商 JVer",
    fill="#FFFFFF",
    font=("Inter SemiBold", 96 * -1)
)

canvas.create_rectangle(
    100.0,
    203.0,
    1338.0,
    205.0,
    fill="#FFFFFF",
    outline="")

#107 Torikeshi
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: window.destroy(),
    relief="flat"
)
button_1.place(
    x=728.0,
    y=608.0,
    width=618.0,
    height=78.0
)


#106 Nyuushukko
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=728.0,
    y=487.0,
    width=618.0,
    height=78.0
)

#105 Tanaoroshi
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=728.0,
    y=367.0,
    width=618.0,
    height=78.0
)

#104 Chuumon Rireki
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=728.0,
    y=247.0,
    width=618.0,
    height=78.0
)


#103 Uriage Shoukai
button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=102.0,
    y=607.0,
    width=618.0,
    height=78.0
)


#102 Chuumon
button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=102.0,
    y=487.0,
    width=618.0,
    height=78.0
)


#101 Shouhin Touroku
button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7"),
    relief="flat"
)
button_7.place(
    x=102.0,
    y=367.0,
    width=618.0,
    height=78.0
)


#100 Jusho Touroku
button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=open_win_rec,
    relief="flat"
)
button_8.place(
    x=102.0,
    y=247.0,
    width=618.0,
    height=78.0
)


window.resizable(False, False)
window.mainloop()
