
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./record/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


rec_window = Tk()
rec_window.title("Record")

rec_window.geometry("1440x1024")
rec_window.configure(bg = "#FFFFFF")


canvas = Canvas(
    rec_window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    720.0,
    512.0,
    image=image_image_1
)

canvas.create_text(
    164.0,
    309.0,
    anchor="nw",
    text="Phone Number",
    fill="#FFFFFF",
    font=("Inter", 40 * -1)
)

canvas.create_text(
    164.0,
    380.0,
    anchor="nw",
    text="Customers Name",
    fill="#FFFFFF",
    font=("Inter", 40 * -1)
)

canvas.create_text(
    164.0,
    451.0,
    anchor="nw",
    text="Postal Code",
    fill="#FFFFFF",
    font=("Inter", 40 * -1)
)

canvas.create_text(
    164.0,
    522.0,
    anchor="nw",
    text="Address 1",
    fill="#FFFFFF",
    font=("Inter", 40 * -1)
)

canvas.create_text(
    164.0,
    593.0,
    anchor="nw",
    text="Address 2",
    fill="#FFFFFF",
    font=("Inter", 40 * -1)
)

canvas.create_text(
    164.0,
    664.0,
    anchor="nw",
    text="Address 3",
    fill="#FFFFFF",
    font=("Inter", 40 * -1)
)

canvas.create_text(
    164.0,
    735.0,
    anchor="nw",
    text="Area",
    fill="#FFFFFF",
    font=("Inter", 40 * -1)
)

canvas.create_text(
    177.0,
    68.0,
    anchor="nw",
    text="住所登録",
    fill="#FFFFFF",
    font=("Inter SemiBold", 96 * -1)
)

canvas.create_rectangle(
    100.0,
    203.0,
    1338.0,
    205.00010681152344,
    fill="#FFFFFF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    778.0,
    323.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFF3FB",
    fg="#000716",
    font='Arial 20 bold',
    highlightthickness=0
)
entry_1.place(
    x=580.0,
    y=298.0,
    width=396.0,
    height=48.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    860.5,
    394.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFF3FB",
    fg="#000716",
    font=16,
    highlightthickness=0
)
entry_2.place(
    x=580.0,
    y=369.0,
    width=561.0,
    height=48.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    675.5,
    465.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFF3FB",
    fg="#000716",
    font=16,
    highlightthickness=0
)
entry_3.place(
    x=580.0,
    y=440.0,
    width=191.0,
    height=48.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    935.5,
    536.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFF3FB",
    fg="#000716",
    font=16,
    highlightthickness=0
)
entry_4.place(
    x=580.0,
    y=511.0,
    width=711.0,
    height=48.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    935.5,
    607.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFF3FB",
    fg="#000716",
    font=16,
    highlightthickness=0
)
entry_5.place(
    x=580.0,
    y=582.0,
    width=711.0,
    height=48.0
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    935.5,
    678.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#FFF3FB",
    fg="#000716",
    font=16,
    highlightthickness=0
)
entry_6.place(
    x=580.0,
    y=653.0,
    width=711.0,
    height=48.0
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    675.5,
    749.0,
    image=entry_image_7
)
entry_7 = Entry(
    bd=0,
    bg="#FFF3FB",
    fg="#000716",
    font=16,
    highlightthickness=0
)
entry_7.place(
    x=580.0,
    y=724.0,
    width=191.0,
    height=48.0
)
rec_window.resizable(False, False)
rec_window.mainloop()
